src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $stock;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="products")
     * @ORM\JoinColumn(nullable=true)
     */
    private $tags;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="products")
     * @ORM\JoinColumn(nullable=true)
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reservation", mappedBy="product")
     * @ORM\JoinColumn(nullable=true)
     */
    private $reservations;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->reservations = new ArrayCollection();
    }

    public function getCategoryType(): string 
    {
        //Cette fonction sert à préciser le type de catégorie de notre Product pour la Vue
        //Si la catégorie n'existe pas, le if est validé et la seconde condition n'est pas lue
        if(!$this->category || $this->category->getName() == 'Autre') {
            return 'none';
        } else return strtolower($this->category->getName());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setProduct($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getProduct() === $this) {
                $reservation->setProduct(null);
            }
        }

        return $this;
    }
}

templates/index/dataform.html.twig
{% extends 'base.html.twig' %}

{% block title %}Index - {{ parent() }}{% endblock %}

{% block body %}
	<!-- The Dataform Section -->
	<div class="w3-container w3-content w3-center w3-padding-64" style="max-width:800px" id="band">
    {# formName et dataForm seront transmis au Controller pour renseigner le titre et le formulaire #}
		<h2 class="w3-wide">{{ formName }}</h2>
		{{ form(dataForm) }}
	</div>
{% endblock %}

templates/index/fiche-produit.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ parent() }} - Fiche produit {% endblock %}

{% block body %}

	<div class="w3-container w3-content w3-center w3-padding-64" style="max-width:800px" id="produitmobilier">
		<h2 class="w3-wide w3-center">FICHE PRODUIT: {{ product.name }}</h2>
		<p class="w3-opacity w3-center">
			<i>ProduitsMobilier.store</i>
		</p><br>
		<div class="w3-row-padding w3-padding-32" style="margin:0 -16px">
			<div class="w3-third w3-margin-bottom" style="width:65%">
				<img src="{{ asset('/assets/img/placeholder_' ~ product.categoryType ~ '.jpg') }}" class="w3-round w3-hover-opacity" style="width: 300px;" alt="Produit">
				<div class="w3-container w3-white">
					<p>
						<b>{{ product.name }}</b>
					</p>
					<p>
						<b>Tags:</b>
						{% if product.tags is empty %}
                    		Aucun
                		{% else %}
                    		{% for tag in product.tags %}
                        		<a href="{{path('index_tag', {'tagId':tag.id})}}">{{ tag.name }}</a>;
                    		{% endfor %}
                		{% endif %}
					</p>
				</div>
			</div>
			<div class="w3-third w3-margin-bottom" style="width:33%">
				<div class="w3-container w3-white">
					<p>
						<b>{{ product.name }}</b>
					</p>
					<p class="w3-opacity">Stock: {{ product.stock }} unités disponibles</p>
					<p class="w3-opacity">Prix: {{ product.price }} €</p>
					<p>{{ product.description }}</p>
					{% if is_granted('ROLE_USER') %}
						{% if product.stock == 0 %}
						<p class="w3-text-red">Produit épuisé<p>
						{% else %}
							{{ form(buyForm) }}
						{% endif %}
					{% endif %}
				</div>
			</div>
		</div>
	</div>

{% endblock %}

templates/index/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Index - {{ parent() }}{% endblock %}

{% block body %}
    <!-- The Band Section -->
    <div class="w3-container w3-content w3-center w3-padding-64" style="max-width:800px" id="band">
        <h2 class="w3-wide w3-margin-bottom">Bienvenue
        {% if user is not null %}
            {{ user.username }} !
        {% else %}
            Visiteur !
        {% endif %}
        </h2>
        <h2 class="w3-wide">CATALOGUE</h2>
        <p class="w3-opacity">
            <i>We love music</i>
        </p>
        <p class="w3-justify">We have created a fictional band website. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
        ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur
        adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
        <div class="w3-row w3-padding-32">
            {% for product in products %}
                <div class="w3-third">
                    <p>{{ product.name }}</p>
                    <a href="{{ path('product_fiche', { 'productId' : product.id }) }}"><img src="{{ asset('/assets/img/placeholder_' ~ product.categoryType ~ '.jpg') }}" class="w3-round w3-margin-bottom" alt="Random Name" style="width:60%"></a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/index/taglist.html.twig
{% extends 'base.html.twig' %}

{% block title %}TagList --
	{{ parent() }}
{% endblock %}

{% block body %}
	<div class="w3-container w3-content w3-padding-64" style="max-width:800px" id="dashboard">
		<div class="w3-center">
			<h1 class="w3-wide">LISTE DES TAGS</h1>

			<ul class="w3-ul w3-border-white w3-white">
				{% for tag in tags %}
					<li class="w3-padding">
						<p>
							{{ tag.name }}
							<a href="{{ path('index_tag', {'tagId' : tag.id}) }}">
								<button class="w3-button w3-blue-gray" style="float:right;">Parcourir</button>
							</a>
						</p>
					</li>
				{% endfor %}
			</ul>


		</div>
	</div>
{% endblock %}